name: Environment Selection Example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  show-env:
    runs-on: ubuntu-latest

    steps:
      - name: Show selected environment
        run: echo "You selected ${{ github.event.inputs.environment }} environment"
