name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "dev"
        type: choice
        options:
          - {input.environment}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show selected environment
        run: echo "Environment selected: ${{ github.event.inputs.environment }}"

      - name: Run deployment
        run: |
          case "${{ github.event.inputs.environment }}" in
            dev)
              echo "🚀 Deploying to Development environment..."
              ;;
            qa)
              echo "🧪 Deploying to QA environment..."
              ;;
            prod)
              echo "🔥 Deploying to Production environment..."
              ;;
          esac
